// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://envhrpmkilypajdlbeuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVudmhycG1raWx5cGFqZGxiZXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjI3MTAsImV4cCI6MjA3MzU5ODcxMH0.THmXaMvLt03m6iq0XThC05mbM-zVEdAb4NI9HtMioNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});